### ISSUE TITLE
Type cast error when running addDemographics() any tips?

### ISSUE THREAD

**Issue by pa-nathaniel** [cran/PatientProfiles#1]
Hi PatientProfiles team,

Really excited to use the package! Unfortunately I ran into an error when trying `addDemographics()` I was hoping to get some guidance on.

I have an object called `x` which is a list containing `tables_cdm`, a `cdm_reference` object created from `CDMConnector::cdm_from_con()`, and `cohort_tbl`, a connection to a a cohort table created by `DBI::dbConnect()`. The tables are on Redshift.

Here are some metadata about the objects:

```
class(x$tables_cdm)
# cdm_reference

class(x$cohort_tbl)
# [1] "tbl_PqConnection" "tbl_dbi"          "tbl_sql"          "tbl_lazy"         "tbl"  

colnames(x$cohort_tbl)
# [1] "cohort_definition_id" "subject_id"           "cohort_start_date"    "cohort_end_date" 
```

Unfortunately, when I call `addDemographics()`, I get the following error about a mismatch in types.

```
addDemographics(x$cohort_tbl, cdm = x$tables_cdm)
Error in `db_save_query.DBIConnection()`:
! Can't save query to "dbplyr_011".
Caused by error:
! Failed to fetch row: ERROR:  function concat_ws("unknown", character varying, "unknown", character varying, "unknown", character varying) does not exist
HINT:  No function matches the given name and argument types. You may need to add explicit type casts.
Run `rlang::last_trace()` to see where the error occurred.
```
Note that I am, however, able to perform joins on the tables directly just fine. For example, the following code works:

```
# This works fine
x$cohort_tbl |> dplyr::left_join(x$tables_cdm$person)
``

Any tips on what could be causing this issue and how to debug?

**Comment by gaborcsardi** [comment]
Hi, this is a read only mirror of CRAN, please see the package authors in the `DESCRIPTION` file. Look for `Maintainer`, `BugReports` and `URL`. Thanks!
